### ISSUE TITLE
请更正我的名字

### ISSUE THREAD

**Issue by wyfcyx** [xiyurain/UltraOS#1]
《UltraOS文档》第五页中我的名字打错了，应为“吴一凡”，请更正一下，谢谢。

**Comment by xiyurain** [comment]
非常抱歉！无意冒犯，这是由于我们在编写文档的时候赶进度而疏忽造成的，今天之内更改过来。
感谢指正

**Comment by wyfcyx** [comment]
没关系的:)
感谢你们杰出的工作！

**Comment by xiyurain** [comment]
0v0 
好的，感谢大佬的rCore-Tutorial，作为我们队伍学习rust & os以及开发这个项目的基础和指引。
